%Project Description: Generates a matrix and replaces the values of the
%matrix based on the random positions generated by the user input
%Date: 4/05/2018

clc;
clear;
matrix=['1 ABC DEF';'2 ABC DEF';'3 ABC DEF';'4 ABC DEF';'5 ABC DEF';'6 ABC DEF';'7 ABC DEF';];

loop= 'y';  %the input to ask the user for continuation of the program

while(loop=='y'  || loop=='Y' ) %while loop to continue program
    clc;
s=1; 
while(s==1) 
    %receives the input from the user for the number of random integers to be generated in the array
    num=input('Please enter an integer between 1 and 15: '); 
    if(fix(num)~=num) %checks if integer
        s=1;
        disp('The value you entered is not an integer.');
    elseif((num>=1)&&(num<=15)) %checks if between 1 and 15
        s=0;
        disp(['You entered: ', num2str(num)]);
        disp(' ');
    else
        s=1;
        disp('The number you entered in not within the range. Please try again.');
        disp(' ');
    end
end
%the original matrix has 7 rows
Xmin=1; 
Xmax=8;
%the original matrix has 9 columns
Ymin=3;
Ymax=10;

d=1;
while(d) %===========loop(1)
    x=fix(Xmin+rand(1,num)*(Xmax-Xmin));
    
    check=1; %checks if the generated y value is 6 as matrix(x,6) has ' ' space which should not be replaced by 'X'
    while(check)
        y=fix(Ymin+rand(1,num)*(Ymax-Ymin));
    
        for loop=1:num
            if(y(1,loop)==6)
                check=1;
                break; %breaks from for loop if at least one of the value in y is 6
            else
                check=0;
            end
        end
    end
    random_x=x;
    random_y=y;
    
    e=0; 
    for j=1:num %===========loop(2)
        if(e==0)
            for k=(j+1):num %===========loop(3)
                
                %checks if the x indices are same AND then checks if the y indices are same
                if ((random_x(1,j)==random_x(1,k))&&(random_y(1,j)==random_y(1,k)))
                    %disp('x');
                    d=1; 
                    e=1; %breaks loop (2)
                    break %breaks loop (3)
                else
                         d = 0; %breaks loop (1)
                end
            end
        end
    end
end

matrix_temp=matrix;
for iter=1:num
    j=random_x(1, iter);
    k=random_y(1, iter);
    matrix_temp(j, k)='X'; %replaces the random positions with 'X'
end

disp('Original Matrix');
disp(matrix);
disp(' ');
disp('Modified Matrix');
disp(matrix_temp);

disp('  ');
%prompts user to type 'y/Y' or something else to continue or quit programrespectively
loop=input('Do you want to continue? (y/Y to continue; any other quits the program) ' ,  's');
clc; 
end

